application: ae-12-ajax
runtime: python27
version : 1
threadsafe: false
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /reset
  script: index.py
  login: admin
  
- url: /.*
  script: index.py
